"""Add is_recommended column to products

Revision ID: 386dae496305
Revises: ec3d2be62627
Create Date: 2025-11-23 21:22:09.589649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '386dae496305'
down_revision = 'ec3d2be62627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_popular', sa.Boolean(), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_recommended', sa.Boolean(), nullable=True))

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permissions', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('permissions')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('is_recommended')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('is_popular')

    # ### end Alembic commands ###
