"""Add PromoCodeCampaign and Category image support

Revision ID: ec3d2be62627
Revises: 
Create Date: 2025-11-23 15:27:18.987355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec3d2be62627'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo_code_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promo_code_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('recipient_count', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_codes.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('promo_code_campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promo_code_campaigns_promo_code_id'), ['promo_code_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_promo_code_campaigns_sender_id'), ['sender_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promo_code_campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promo_code_campaigns_sender_id'))
        batch_op.drop_index(batch_op.f('ix_promo_code_campaigns_promo_code_id'))

    op.drop_table('promo_code_campaigns')
    # ### end Alembic commands ###
